version: '3'
services:
        db:
                #imagem
                image: mysql:5.5
                #sempre iniciar com o SO
                restart: always
                container_name: mysql_wordpress_compose
                #subnet que ira utilizar
                networks:
                        - net-backend
                #pertinência dos dados
                volumes:
                        - db_data:/var/lib/mysql
                #comandos da imagem, criados pelo autor da imagem
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_DATABASE: wordpress
                        MYSQL_USER: wordpress
                        MYSQL_PASSWORD: wordpress
        
        wordpress:
                image: wordpress:4.7-php5.6
                restart: always
                container_name: wordpress_compose
                networks:
                        - net-backend
                ports:
                        - "9090:80"
                environment:
                        WORDPRESS_DB_HOST: db:3306
                        WORDPRESS_DB_NAME: wordpress
                        WORDPRESS_DB_USER: wordpress
                        WORDPRESS_DB_PASSWORD: wordpress

networks:
        net-backend:

volumes:
        db_data:


