apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teste-pvc
spec:
  accessModes:
  - ReadWriteOnce # gp2 aceita apenas ReadWriteOnce
  resources:
    requests:
      storage: 9Gi
  storageClassName: gp2 # mude para o storageclass da sua provedora de nuvem na ovh uso também "csi-cinder-high-speed"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-demo
  name: nfs-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-demo
  template:
    metadata:
      labels:
        app: nfs-demo
    spec:
      containers:
        - name: web
          image: nginx
          ports:
            - name: web
              containerPort: 80
          volumeMounts:
            # name must match the volume name below
            - name: gp2-vol
              mountPath: "/usr/share/nginx/html/teste"
      volumes:
        - name: gp2-vol
          persistentVolumeClaim:
            claimName: teste-pvc
            readOnly: false