apiVersion: v1
kind: Service
metadata:
  name: helloflask-service
  labels:
    app: helloflask
spec:
  ports:
    - port: 8080 # the port that this service should serve on
      targetPort: 5000 #Container Port
      protocol: TCP
  selector:
    app: helloflask
