apiVersion: v1
kind: Pod
metadata:
  name: busybox-configmap
  namespace: default
spec:
  containers:
  - image: busybox
    name: busy-configmap
    command:
      - sleep
      - "3600"

    envFrom:
    - configMapRef:
        name: cores-frutas
# para env específicos
      # env:
    # - name: frutas
    #   valueFrom:
    #     configMapKeyRef:
    #       name: cores-frutas
    #       key: preferido
