version: '3.7'

services:

  # # Elasticsearch Docker Images: https://www.docker.elastic.co/
  # elasticsearch1:
  #   image: elasticsearch:2.4
  #   container_name: elasticsearch1
  #   environment:
  #     - xpack.security.enabled=false
  #     - discovery.type=single-node
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
  #   mem_limit: 4g
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   cap_add:
  #     - IPC_LOCK 


  #   ports:
  #     - 9201:9200
  #     - 9301:9300

  elasticsearch2:
    image: elasticsearch:8.4.0
    container_name: elasticsearch2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    mem_limit: 4g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK

    ports:
      - 9202:9200
      - 9302:9300
