apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      serviceAccountName: k8s-s3-role
      containers:
        - name: ubuntu
          image: ubuntu
          command: ["/bin/sleep", "3650d"]
          # resources:
          #   requests:
          #     memory: "1G"
          #     cpu: "100m"
          #   limits:
          #     memory: "2G"
          #     cpu: "200m"

