apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: distributedtracing
  name: distributedtracing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distributedtracing
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: distributedtracing
    spec:
      containers:
      - image: 138272065686.dkr.ecr.us-east-1.amazonaws.com/core_distributedtracing
        name: distributedtracing
        resources: {}
status: {}
