apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gatewayapi
  name: gatewayapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayapi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gatewayapi
    spec:
      containers:
      - image: 138272065686.dkr.ecr.us-east-1.amazonaws.com/core_gatewayapi
        name: gatewayapi
        resources: {}
status: {}
