apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: materaintegrator
  name: materaintegrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: materaintegrator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: materaintegrator
    spec:
      containers:
      - image: 138272065686.dkr.ecr.us-east-1.amazonaws.com/core_materaintegrator
        name: materaintegrator
        imagePullPolicy: Always
        resources: 
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
terminationGracePeriodSeconds: 30
status: {}
