apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: whitelistapiaccount
  name: whitelistapiaccount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whitelistapiaccount
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: whitelistapiaccount
    spec:
      containers:
      - image: 138272065686.dkr.ecr.us-east-1.amazonaws.com/core_whitelistapiaccount
        name: whitelistapiaccount
        resources: {}
status: {}
