# version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    # container_name: my-mysql
    # restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    ports:
      - 8080:8080
