#imagem usada do docker hub
FROM amazonlinux:latest
#informações de quem criou
MAINTAINER Humberto Moura <humbertomoura.n@gmail.com>

RUN yum update -y
RUN yum install vim screen wget htop nc jq -y


